### ISSUE TITLE
Questions in scHiCTools

### ISSUE THREAD

**Issue by sshen82** [liu-bioinfo-lab/scHiCTools#3]
Hi,
Thank you for this great software! However, I encountered two problems right now.

The first is that I don't really understand the format of the input data. Right now I have txt files looking like the input of "scHiCluster", which is like below:
1 1 9
1 2 1
.....
The first two columns are positions, and the third is count number. Which format does this belong to? matrix_txt?

The second question is that in my code, I wrote explicitly that chromosomes='chr1' (and I only have data in chr1 in that folder.), however, it asks for chr2. Did I do something wrong?

loaded_data = scHiCs(
    files, sparse=True, reference_genome='mm9',
    resolution=1000000, keep_n_strata=10,
    format='matrix_txt', adjust_resolution=False, header=0, chromosomes='chr1',
    operations=['convolution']
    )

Processing 1 out of 1 files: C:/Users/solei/Downloads/Ren/FreeHiC_sc/2i
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "C:\Users\solei\miniconda3\envs\scHiCTools\lib\site-packages\schictools-0.0.3-py3.7.egg\scHiCTools\load\ContactMaps.py", line 142, in __init__
    **kwargs)
  File "C:\Users\solei\miniconda3\envs\scHiCTools\lib\site-packages\schictools-0.0.3-py3.7.egg\scHiCTools\load\load_hic_file.py", line 166, in load_HiC
    mat = np.loadtxt('{0}/{1}.txt'.format(file, chromosome))
  File "C:\Users\solei\miniconda3\envs\scHiCTools\lib\site-packages\numpy-1.19.1-py3.7-win-amd64.egg\numpy\lib\npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\solei\miniconda3\envs\scHiCTools\lib\site-packages\numpy-1.19.1-py3.7-win-amd64.egg\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\solei\miniconda3\envs\scHiCTools\lib\site-packages\numpy-1.19.1-py3.7-win-amd64.egg\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: C:/Users/solei/Downloads/Ren/FreeHiC_sc/2i/chr2.txt not found.

Yours Sincerely,
Siqi Shen

**Comment by sshen82** [comment]
I see the customized option, and know how to do this. Thanks!
